export type ResourceType = "NOTES" | "DPP" | "FORMULA_SHEET" | "MIND_MAP";
export type ResourceExam = "JEE_MAIN" | "JEE_ADVANCED" | "NEET";

export const RESOURCE_TYPE_LABELS: Record<ResourceType, string> = {
  NOTES: "Notes PDF",
  DPP: "DPP",
  FORMULA_SHEET: "Formula Sheet",
  MIND_MAP: "Mind Map",
};

export const RESOURCE_EXAM_LABELS: Record<ResourceExam, string> = {
  JEE_MAIN: "JEE Main",
  JEE_ADVANCED: "JEE Advanced",
  NEET: "NEET",
};

export interface Resource {
  id: string;
  title: string;
  description: string;
  type: ResourceType;
  chapterSlug: string;
  chapterTitle: string;
  exams: ResourceExam[];
  pages: number;
  fileSizeKB: number;
  downloadCount: number;
  isFeatured: boolean;
  isNew: boolean;
  fileUrl: string;
}

const RAW_RESOURCES: Omit<Resource, "fileUrl">[] = [
  // ── Notes PDFs ───────────────────────────────────────────────
  {
    id: "n-kin",
    title: "Kinematics — Complete Notes",
    description: "1D & 2D motion, projectile, relative motion. Fully solved examples and derivations.",
    type: "NOTES",
    chapterSlug: "kinematics",
    chapterTitle: "Kinematics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 48,
    fileSizeKB: 2340,
    downloadCount: 8420,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "n-law",
    title: "Laws of Motion — Complete Notes",
    description: "Newton's laws, friction, constraint motion, pseudo-force with solved JEE problems.",
    type: "NOTES",
    chapterSlug: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 52,
    fileSizeKB: 2610,
    downloadCount: 7850,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "n-wep",
    title: "Work, Energy & Power — Notes",
    description: "Work-energy theorem, conservative forces, energy conservation, power.",
    type: "NOTES",
    chapterSlug: "work-energy-power",
    chapterTitle: "Work, Energy & Power",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 44,
    fileSizeKB: 2100,
    downloadCount: 6920,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "n-cm",
    title: "Circular Motion & Rotation — Notes",
    description: "Centripetal acceleration, rotational dynamics, angular momentum, rolling motion.",
    type: "NOTES",
    chapterSlug: "circular-motion",
    chapterTitle: "Circular Motion",
    exams: ["JEE_MAIN", "JEE_ADVANCED"],
    pages: 60,
    fileSizeKB: 3100,
    downloadCount: 5340,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "n-grav",
    title: "Gravitation — Complete Notes",
    description: "Newton's law, gravitational potential, orbits, Kepler's laws, satellites.",
    type: "NOTES",
    chapterSlug: "gravitation",
    chapterTitle: "Gravitation",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 38,
    fileSizeKB: 1890,
    downloadCount: 4810,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "n-es",
    title: "Electrostatics — Complete Notes",
    description: "Coulomb's law, fields, Gauss's law, potential, dipoles, capacitors.",
    type: "NOTES",
    chapterSlug: "electric-charges-and-fields",
    chapterTitle: "Electric Charges & Fields",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 72,
    fileSizeKB: 3850,
    downloadCount: 9120,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "n-ce",
    title: "Current Electricity — Notes",
    description: "Ohm's law, Kirchhoff's laws, Wheatstone bridge, cells in series/parallel.",
    type: "NOTES",
    chapterSlug: "current-electricity",
    chapterTitle: "Current Electricity",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 56,
    fileSizeKB: 2760,
    downloadCount: 7230,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "n-mag",
    title: "Magnetism & Moving Charges — Notes",
    description: "Biot-Savart law, Ampere's law, magnetic force on charges and current loops.",
    type: "NOTES",
    chapterSlug: "moving-charges-and-magnetism",
    chapterTitle: "Moving Charges & Magnetism",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 64,
    fileSizeKB: 3240,
    downloadCount: 5890,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "n-emi",
    title: "Electromagnetic Induction — Notes",
    description: "Faraday's law, Lenz's law, motional EMF, self & mutual inductance, eddy currents.",
    type: "NOTES",
    chapterSlug: "electromagnetic-induction",
    chapterTitle: "Electromagnetic Induction",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 50,
    fileSizeKB: 2500,
    downloadCount: 6410,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "n-wav",
    title: "Waves — Complete Notes",
    description: "Transverse & longitudinal waves, standing waves, beats, Doppler effect.",
    type: "NOTES",
    chapterSlug: "waves",
    chapterTitle: "Waves",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 58,
    fileSizeKB: 2920,
    downloadCount: 5650,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "n-optics",
    title: "Ray Optics — Complete Notes",
    description: "Reflection, refraction, lenses, mirrors, total internal reflection, prisms.",
    type: "NOTES",
    chapterSlug: "ray-optics",
    chapterTitle: "Ray Optics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 66,
    fileSizeKB: 3380,
    downloadCount: 7740,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "n-modern",
    title: "Modern Physics — Notes",
    description: "Photoelectric effect, Bohr model, X-rays, nuclear physics, radioactivity.",
    type: "NOTES",
    chapterSlug: "dual-nature-of-radiation-and-matter",
    chapterTitle: "Modern Physics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 68,
    fileSizeKB: 3500,
    downloadCount: 8960,
    isFeatured: true,
    isNew: true,
  },

  // ── DPPs ─────────────────────────────────────────────────────
  {
    id: "dpp-kin",
    title: "Kinematics DPP Set (10 sheets)",
    description: "200 practice problems covering all kinematics sub-topics. JEE Main + Advanced level.",
    type: "DPP",
    chapterSlug: "kinematics",
    chapterTitle: "Kinematics",
    exams: ["JEE_MAIN", "JEE_ADVANCED"],
    pages: 40,
    fileSizeKB: 1820,
    downloadCount: 5230,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dpp-law",
    title: "Laws of Motion DPP Set (12 sheets)",
    description: "240 problems: Newton's laws, friction, pseudo-force, connected bodies.",
    type: "DPP",
    chapterSlug: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    exams: ["JEE_MAIN", "JEE_ADVANCED"],
    pages: 48,
    fileSizeKB: 2100,
    downloadCount: 4780,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dpp-es",
    title: "Electrostatics DPP Set (15 sheets)",
    description: "300 problems covering Coulomb's law, Gauss's law, capacitors, and potential.",
    type: "DPP",
    chapterSlug: "electric-charges-and-fields",
    chapterTitle: "Electrostatics",
    exams: ["JEE_MAIN", "JEE_ADVANCED"],
    pages: 60,
    fileSizeKB: 2680,
    downloadCount: 6340,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "dpp-ce",
    title: "Current Electricity DPP Set (10 sheets)",
    description: "200 circuit problems: Kirchhoff's laws, meters, combinations, cells.",
    type: "DPP",
    chapterSlug: "current-electricity",
    chapterTitle: "Current Electricity",
    exams: ["JEE_MAIN", "NEET"],
    pages: 40,
    fileSizeKB: 1760,
    downloadCount: 4120,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dpp-mag",
    title: "Magnetism DPP Set (12 sheets)",
    description: "240 problems: magnetic fields, forces, induction — JEE Main & Advanced patterns.",
    type: "DPP",
    chapterSlug: "moving-charges-and-magnetism",
    chapterTitle: "Moving Charges & Magnetism",
    exams: ["JEE_MAIN", "JEE_ADVANCED"],
    pages: 48,
    fileSizeKB: 2040,
    downloadCount: 3870,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "dpp-optics",
    title: "Optics DPP Set (14 sheets)",
    description: "280 problems spanning ray optics, wave optics, and optical instruments.",
    type: "DPP",
    chapterSlug: "ray-optics",
    chapterTitle: "Optics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 56,
    fileSizeKB: 2460,
    downloadCount: 5510,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dpp-neet",
    title: "NEET Physics DPP Mega Set",
    description: "500 NEET-style MCQs across all chapters. Includes PYQ analysis for each topic.",
    type: "DPP",
    chapterSlug: "kinematics",
    chapterTitle: "All Chapters (NEET)",
    exams: ["NEET"],
    pages: 100,
    fileSizeKB: 4800,
    downloadCount: 9870,
    isFeatured: true,
    isNew: true,
  },

  // ── Formula Sheets ───────────────────────────────────────────
  {
    id: "fs-mech",
    title: "Mechanics Formula Sheet",
    description: "All kinematics, dynamics, energy, rotation, gravitation formulas on 2 pages.",
    type: "FORMULA_SHEET",
    chapterSlug: "kinematics",
    chapterTitle: "Mechanics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 2,
    fileSizeKB: 380,
    downloadCount: 14200,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "fs-em",
    title: "Electromagnetism Formula Sheet",
    description: "Electrostatics, current electricity, magnetism, and EMI condensed to 3 pages.",
    type: "FORMULA_SHEET",
    chapterSlug: "electric-charges-and-fields",
    chapterTitle: "Electromagnetism",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 3,
    fileSizeKB: 540,
    downloadCount: 12860,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "fs-waves",
    title: "Waves & Optics Formula Sheet",
    description: "All wave formulas, Snell's law, lens/mirror equations, diffraction grating.",
    type: "FORMULA_SHEET",
    chapterSlug: "waves",
    chapterTitle: "Waves & Optics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 2,
    fileSizeKB: 360,
    downloadCount: 10540,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "fs-modern",
    title: "Modern Physics Formula Sheet",
    description: "Photoelectric effect, Bohr model, X-rays, nuclear decay, semiconductors.",
    type: "FORMULA_SHEET",
    chapterSlug: "dual-nature-of-radiation-and-matter",
    chapterTitle: "Modern Physics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 2,
    fileSizeKB: 340,
    downloadCount: 9320,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "fs-thermo",
    title: "Thermodynamics Formula Sheet",
    description: "Laws of thermodynamics, heat engines, specific heat, kinetic theory.",
    type: "FORMULA_SHEET",
    chapterSlug: "thermodynamics",
    chapterTitle: "Thermodynamics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 2,
    fileSizeKB: 310,
    downloadCount: 7640,
    isFeatured: false,
    isNew: true,
  },

  // ── Mind Maps ─────────────────────────────────────────────────
  {
    id: "mm-kin",
    title: "Kinematics Mind Map",
    description: "One-page visual overview of all kinematics concepts, equations, and connections.",
    type: "MIND_MAP",
    chapterSlug: "kinematics",
    chapterTitle: "Kinematics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 1,
    fileSizeKB: 820,
    downloadCount: 6480,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "mm-es",
    title: "Electrostatics Mind Map",
    description: "Visual mind map linking Coulomb's law, Gauss's law, potential and capacitance.",
    type: "MIND_MAP",
    chapterSlug: "electric-charges-and-fields",
    chapterTitle: "Electrostatics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 1,
    fileSizeKB: 940,
    downloadCount: 5720,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "mm-mag",
    title: "Magnetism Mind Map",
    description: "Complete magnetism concept map: sources, effects, induction — all connected.",
    type: "MIND_MAP",
    chapterSlug: "moving-charges-and-magnetism",
    chapterTitle: "Magnetism",
    exams: ["JEE_MAIN", "JEE_ADVANCED"],
    pages: 1,
    fileSizeKB: 870,
    downloadCount: 4130,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "mm-modern",
    title: "Modern Physics Mind Map",
    description: "Visual overview of quantum phenomena, atomic models, nuclear reactions.",
    type: "MIND_MAP",
    chapterSlug: "dual-nature-of-radiation-and-matter",
    chapterTitle: "Modern Physics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 1,
    fileSizeKB: 910,
    downloadCount: 6890,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "mm-optics",
    title: "Optics Mind Map",
    description: "Ray optics and wave optics connected in a single visual overview.",
    type: "MIND_MAP",
    chapterSlug: "ray-optics",
    chapterTitle: "Optics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 1,
    fileSizeKB: 860,
    downloadCount: 5340,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "mm-thermo",
    title: "Thermodynamics Mind Map",
    description: "Thermodynamic processes, laws, cycles, and kinetic theory in one diagram.",
    type: "MIND_MAP",
    chapterSlug: "thermodynamics",
    chapterTitle: "Thermodynamics",
    exams: ["JEE_MAIN", "JEE_ADVANCED", "NEET"],
    pages: 1,
    fileSizeKB: 830,
    downloadCount: 4560,
    isFeatured: false,
    isNew: true,
  },
];

export const RESOURCES: Resource[] = RAW_RESOURCES.map((r) => ({
  ...r,
  fileUrl: `/api/download/${r.id}`,
}));

export const RESOURCE_STATS = {
  total: RESOURCES.length,
  totalDownloads: RESOURCES.reduce((s, r) => s + r.downloadCount, 0),
  notesPdfs: RESOURCES.filter((r) => r.type === "NOTES").length,
  dpps: RESOURCES.filter((r) => r.type === "DPP").length,
  formulaSheets: RESOURCES.filter((r) => r.type === "FORMULA_SHEET").length,
  mindMaps: RESOURCES.filter((r) => r.type === "MIND_MAP").length,
};

export const FEATURED_RESOURCES = RESOURCES.filter((r) => r.isFeatured);
export const NEW_RESOURCES = RESOURCES.filter((r) => r.isNew);

export function formatFileSize(kb: number): string {
  if (kb >= 1024) return `${(kb / 1024).toFixed(1)} MB`;
  return `${kb} KB`;
}

export function formatDownloadCount(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}
