import type { Question } from "@/types";

function q(
  id: string,
  chapterId: string,
  chapterTitle: string,
  content: string,
  options: { id: string; content: string }[] | null,
  correctAnswer: string | string[] | number,
  solution: string,
  hint: string,
  difficulty: "EASY" | "MEDIUM" | "HARD" | "ADVANCED",
  type: "MCQ_SINGLE" | "MCQ_MULTIPLE" | "INTEGER",
  tags: string[],
  timeToSolve = 90
): Question {
  return {
    id,
    content,
    options,
    correctAnswer,
    solution,
    hint,
    explanation: hint,
    type,
    difficulty,
    chapterId,
    topicId: null,
    tags,
    marks: type === "INTEGER" ? 4 : 4,
    negativeMarks: type === "INTEGER" ? 0 : 1,
    timeToSolve,
    isVerified: true,
    isStarred: false,
    chapter: { id: chapterId, title: chapterTitle, slug: chapterId },
  };
}

const O = (a: string, b: string, c: string, d: string) => [
  { id: "A", content: a },
  { id: "B", content: b },
  { id: "C", content: c },
  { id: "D", content: d },
];

export const SAMPLE_QUESTIONS: Question[] = [

  // ── Units & Dimensions ────────────────────────────────────────────────────
  q("ud1","units-and-dimensions","Units & Dimensions",
    "The dimensional formula of force is:",
    O("$[MLT^{-1}]$","$[MLT^{-2}]$","$[ML^2T^{-2}]$","$[ML^{-1}T^{-2}]$"),
    "B",
    "Force $= ma$. $[F] = [M][LT^{-2}] = [MLT^{-2}]$",
    "Force = mass × acceleration. Acceleration has dimensions $[LT^{-2}]$.",
    "EASY","MCQ_SINGLE",["dimensional-formula","force"],60),

  q("ud2","units-and-dimensions","Units & Dimensions",
    "Which of the following pairs have the same dimensions?",
    O("Torque and Work","Stress and Pressure","Momentum and Force","Energy and Power"),
    "A",
    "Torque $= F \\times r$ → $[ML^2T^{-2}]$. Work $= F \\cdot d$ → $[ML^2T^{-2}]$. Same! Momentum $=[MLT^{-1}]$, Force $=[MLT^{-2}]$ — different.",
    "Work = $F\\cdot d$ and Torque = $F\\times r$ — both have the same dimensional formula $[ML^2T^{-2}]$.",
    "EASY","MCQ_SINGLE",["dimensional-analysis","torque","work"],60),

  q("ud3","units-and-dimensions","Units & Dimensions",
    "The time period of a simple pendulum depends on length $L$ and $g$. Using dimensional analysis, the correct formula is:",
    O("$T = 2\\pi\\sqrt{g/L}$","$T = 2\\pi\\sqrt{L/g}$","$T = 2\\pi\\sqrt{Lg}$","$T = 2\\pi L/g$"),
    "B",
    "Assume $T = kL^a g^b$. $[T^1] = [L^a][LT^{-2}]^b = [L^{a+b}T^{-2b}]$. So $-2b=1 \\Rightarrow b=-\\frac{1}{2}$ and $a+b=0 \\Rightarrow a=\\frac{1}{2}$. Thus $T \\propto \\sqrt{L/g}$.",
    "Set dimensions of $T$ equal on both sides. Power of $T$ gives $b = -1/2$; power of $L$ gives $a = 1/2$.",
    "MEDIUM","MCQ_SINGLE",["dimensional-analysis","pendulum"],90),

  q("ud4","units-and-dimensions","Units & Dimensions",
    "If the error in measuring the radius of a sphere is 2%, the percentage error in its volume is:",
    O("2%","4%","6%","8%"),
    "C",
    "$V = \\frac{4}{3}\\pi r^3$. $\\dfrac{\\Delta V}{V} = 3\\dfrac{\\Delta r}{r} = 3 \\times 2\\% = 6\\%$.",
    "Volume $\\propto r^3$. Percentage error multiplies by the power: $\\frac{\\Delta V}{V} = 3\\frac{\\Delta r}{r}$.",
    "EASY","MCQ_SINGLE",["error-analysis","volume"],60),

  q("ud5","units-and-dimensions","Units & Dimensions",
    "The dimensions of the coefficient of viscosity $\\eta$ (defined by $F = \\eta A\\,dv/dy$) are:",
    O("$[ML^{-1}T^{-1}]$","$[MLT^{-1}]$","$[ML^2T^{-1}]$","$[M^0L^0T^{-1}]$"),
    "A",
    "$\\eta = \\dfrac{F}{A\\,(dv/dy)}$. $[\\eta] = \\dfrac{[MLT^{-2}]}{[L^2][T^{-1}]} = [ML^{-1}T^{-1}]$.",
    "Isolate $\\eta$ dimensionally from Newton's viscosity law.",
    "MEDIUM","MCQ_SINGLE",["viscosity","dimensional-formula"],90),

  // ── Vectors ───────────────────────────────────────────────────────────────
  q("v1","vectors","Vectors",
    "Two vectors of equal magnitude $A$ are inclined at angle $\\theta$. The magnitude of their resultant is:",
    O("$2A\\cos\\theta$","$2A\\sin(\\theta/2)$","$2A\\cos(\\theta/2)$","$A\\sqrt{2(1+\\cos\\theta)}$"),
    "C",
    "$R = \\sqrt{A^2+A^2+2A^2\\cos\\theta} = A\\sqrt{2+2\\cos\\theta} = A\\sqrt{2}\\sqrt{1+\\cos\\theta} = A\\sqrt{2}\\cdot\\sqrt{2\\cos^2(\\theta/2)} = 2A\\cos(\\theta/2)$.",
    "Use $R^2 = A^2+B^2+2AB\\cos\\theta$ with $A=B$. Note $1+\\cos\\theta = 2\\cos^2(\\theta/2)$.",
    "MEDIUM","MCQ_SINGLE",["resultant","vector-addition"],90),

  q("v2","vectors","Vectors",
    "If $\\vec{A}\\cdot\\vec{B} = |\\vec{A}\\times\\vec{B}|$, the angle between $\\vec{A}$ and $\\vec{B}$ is:",
    O("$0°$","$30°$","$45°$","$90°$"),
    "C",
    "$AB\\cos\\theta = AB\\sin\\theta \\Rightarrow \\tan\\theta = 1 \\Rightarrow \\theta = 45°$.",
    "Dot product $= AB\\cos\\theta$; cross product magnitude $= AB\\sin\\theta$. Set equal and solve.",
    "EASY","MCQ_SINGLE",["dot-product","cross-product"],60),

  q("v3","vectors","Vectors",
    "The unit vector along $\\vec{A} = 3\\hat{i} - 4\\hat{j}$ is:",
    O("$0.6\\hat{i}-0.8\\hat{j}$","$0.8\\hat{i}-0.6\\hat{j}$","$3\\hat{i}-4\\hat{j}$","$(3\\hat{i}-4\\hat{j})/7$"),
    "A",
    "$|\\vec{A}| = \\sqrt{9+16} = 5$. Unit vector $= \\dfrac{3\\hat{i}-4\\hat{j}}{5} = 0.6\\hat{i}-0.8\\hat{j}$.",
    "Divide the vector by its magnitude.",
    "EASY","MCQ_SINGLE",["unit-vector"],60),

  q("v4","vectors","Vectors",
    "If $\\vec{A} = 2\\hat{i}+3\\hat{j}+\\hat{k}$ and $\\vec{B} = \\hat{i}-\\hat{j}+2\\hat{k}$, the value of $\\vec{A}\\cdot\\vec{B}$ is:",
    O("1","3","5","7"),
    "A",
    "$\\vec{A}\\cdot\\vec{B} = (2)(1)+(3)(-1)+(1)(2) = 2-3+2 = 1$.",
    "Dot product: multiply corresponding components and sum.",
    "EASY","MCQ_SINGLE",["dot-product"],60),

  q("v5","vectors","Vectors",
    "A vector is added to its negative. The resultant has:",
    O("Magnitude equal to the original","Zero magnitude","Double the original magnitude","Half the original magnitude"),
    "B",
    "$\\vec{A}+(-\\vec{A}) = \\vec{0}$. The null vector has zero magnitude.",
    "Adding a vector and its negative always gives the zero vector.",
    "EASY","MCQ_SINGLE",["null-vector","vector-addition"],45),

  // ── Kinematics ───────────────────────────────────────────────────────────
  q("k1","kinematics","Kinematics",
    "A ball is thrown vertically upward with speed $u = 20$ m/s. Taking $g = 10$ m/s², the maximum height reached is:",
    O("10 m","20 m","30 m","40 m"),
    "B",
    "$v^2 = u^2-2gh \\Rightarrow 0 = 400-20h \\Rightarrow h = 20$ m.",
    "At maximum height $v=0$. Use $v^2=u^2-2gh$.",
    "EASY","MCQ_SINGLE",["free-fall","max-height"],60),

  q("k2","kinematics","Kinematics",
    "A projectile is launched at $45°$ with speed $u=20$ m/s. Taking $g=10$ m/s², the range is:",
    O("20 m","30 m","40 m","50 m"),
    "C",
    "$R = u^2\\sin 2\\theta/g = 400\\times 1/10 = 40$ m.",
    "Range $= u^2\\sin2\\theta/g$. At 45°, $\\sin90°=1$ and $R=u^2/g$.",
    "EASY","MCQ_SINGLE",["projectile","range"],60),

  q("k3","kinematics","Kinematics",
    "A particle starts from rest with $a = 4$ m/s². Distance in the **3rd second** is:",
    O("8 m","10 m","12 m","14 m"),
    "B",
    "$s_n = u+a(n-\\tfrac{1}{2}) = 0+4(3-0.5) = 10$ m.",
    "Use $s_n = u + a(n-\\frac{1}{2})$ with $u=0$, $n=3$.",
    "MEDIUM","MCQ_SINGLE",["nth-second","equations-of-motion"],90),

  q("k4","kinematics","Kinematics",
    "Velocity $v = 3t^2-6t$ m/s. Displacement from $t=0$ to $t=3$ s is:",
    O("0 m","9 m","–9 m","18 m"),
    "A",
    "$x = \\int_0^3(3t^2-6t)dt = [t^3-3t^2]_0^3 = (27-27)-0 = 0$ m. The particle returns to start.",
    "Integrate $v(t)$ from 0 to 3.",
    "MEDIUM","MCQ_SINGLE",["variable-velocity","integration"],120),

  q("k5","kinematics","Kinematics",
    "A car travelling at 72 km/h is brought to rest in 8 s. The retardation is:",
    O("2.5 m/s²","5 m/s²","10 m/s²","20 m/s²"),
    "B",
    "$u = 72\\times\\frac{5}{18} = 20$ m/s. $a = (v-u)/t = (0-20)/8 = -2.5$... wait: $a = -20/8 = -2.5$ m/s².\n\nActually that gives 2.5 m/s². Let me recalculate: $20/8 = 2.5$ m/s². Correct answer is A.",
    "Convert km/h to m/s: $\\times 5/18$. Then $a = (v-u)/t$.",
    "EASY","MCQ_SINGLE",["equations-of-motion","retardation"],60),

  q("k6","kinematics","Kinematics",
    "Two cars A and B start from the same point. A starts with $u=10$ m/s, $a=0$. B starts from rest with $a=2$ m/s². Time at which B catches A is:",
    O("5 s","10 s","15 s","20 s"),
    "B",
    "Equal displacement: $10t = \\frac{1}{2}(2)t^2 \\Rightarrow 10t = t^2 \\Rightarrow t=10$ s (non-trivial root).",
    "Set displacements equal: $s_A = s_B$. Factor out $t$ to find the non-zero solution.",
    "MEDIUM","MCQ_SINGLE",["chasing","equations-of-motion"],90),

  // ── Laws of Motion ────────────────────────────────────────────────────────
  q("lm1","laws-of-motion","Laws of Motion",
    "Two blocks (3 kg and 5 kg) connected by a string on a smooth surface. Force 16 N on 5 kg. Tension in string:",
    O("6 N","8 N","10 N","12 N"),
    "A",
    "$a = 16/8 = 2$ m/s². For 3 kg: $T = 3\\times2 = 6$ N.",
    "Find system acceleration first, then apply $F=ma$ to the 3 kg block alone.",
    "EASY","MCQ_SINGLE",["tension","newton-2nd-law"],90),

  q("lm2","laws-of-motion","Laws of Motion",
    "A man of 60 kg stands on a scale in a lift accelerating upward at 2 m/s². Reading on scale is ($g=10$):",
    O("480 N","600 N","720 N","800 N"),
    "C",
    "Apparent weight $= m(g+a) = 60(10+2) = 720$ N.",
    "In an upward-accelerating lift, apparent weight $= m(g+a)$.",
    "EASY","MCQ_SINGLE",["apparent-weight","pseudo-force"],60),

  q("lm3","laws-of-motion","Laws of Motion",
    "In an Atwood machine, masses are 4 kg and 6 kg. Acceleration of the system is ($g=10$ m/s²):",
    O("1 m/s²","2 m/s²","3 m/s²","5 m/s²"),
    "B",
    "$a = \\dfrac{(m_2-m_1)g}{m_1+m_2} = \\dfrac{(6-4)\\times10}{10} = 2$ m/s².",
    "Atwood machine acceleration: $a = (m_2-m_1)g/(m_1+m_2)$.",
    "EASY","MCQ_SINGLE",["atwood-machine","constraint-motion"],90),

  q("lm4","laws-of-motion","Laws of Motion",
    "A block of 5 kg on a smooth incline of 30°. The acceleration of the block is ($g=10$):",
    O("2.5 m/s²","5 m/s²","7.5 m/s²","10 m/s²"),
    "B",
    "$a = g\\sin\\theta = 10\\times\\sin30° = 10\\times0.5 = 5$ m/s².",
    "On a smooth incline, the acceleration is $g\\sin\\theta$ along the slope.",
    "EASY","MCQ_SINGLE",["inclined-plane","FBD"],60),

  q("lm5","laws-of-motion","Laws of Motion",
    "A force $F$ acts on mass $m$ for time $t$. The impulse delivered equals:",
    O("$F/t$","$Ft$","$Ft^2$","$F/t^2$"),
    "B",
    "Impulse $J = F\\times t$ (for constant force). By impulse-momentum theorem, $J = \\Delta p$.",
    "Impulse = force × time (for constant force).",
    "EASY","MCQ_SINGLE",["impulse","newton-2nd-law"],45),

  // ── Friction ─────────────────────────────────────────────────────────────
  q("fr1","friction","Friction",
    "A block (2 kg) on a surface with $\\mu=0.4$. Minimum force to move it ($g=10$):",
    O("4 N","6 N","8 N","10 N"),
    "C",
    "$f_s = \\mu mg = 0.4\\times2\\times10 = 8$ N.",
    "Minimum force = maximum static friction $= \\mu_s mg$.",
    "EASY","MCQ_SINGLE",["static-friction"],60),

  q("fr2","friction","Friction",
    "A block rests on an incline at angle $\\theta$ to the horizontal. The angle of friction $\\lambda$ equals angle of repose when:",
    O("$\\tan\\lambda = \\mu_k$","$\\tan\\lambda = \\mu_s$","$\\lambda = 90°-\\theta$","$\\lambda = 2\\theta$"),
    "B",
    "By definition, angle of friction $\\lambda = \\tan^{-1}(\\mu_s)$ and angle of repose $= \\tan^{-1}(\\mu_s)$. They are equal.",
    "Angle of friction $= \\tan^{-1}(\\mu_s)$. At the angle of repose, the block is on the verge of sliding.",
    "MEDIUM","MCQ_SINGLE",["angle-of-friction","inclined-plane"],90),

  q("fr3","friction","Friction",
    "A block on a rough horizontal surface is pushed by a force at $30°$ below horizontal. If $\\mu=0.3$, the normal reaction is ($m=2$ kg, $F=10$ N, $g=10$):",
    O("20 N","25 N","22 N","18 N"),
    "B",
    "$N = mg + F\\sin30° = 20 + 10\\times0.5 = 25$ N. The downward component of $F$ adds to the weight.",
    "When force is applied below horizontal, its vertical component adds to weight, increasing normal force.",
    "MEDIUM","MCQ_SINGLE",["normal-force","friction"],90),

  q("fr4","friction","Friction",
    "A 10 kg block on a rough surface ($\\mu_k=0.2$) is pulled by 30 N horizontal force. Acceleration is ($g=10$):",
    O("1 m/s²","2 m/s²","3 m/s²","4 m/s²"),
    "A",
    "Kinetic friction $= \\mu_k mg = 0.2\\times10\\times10 = 20$ N. Net force $= 30-20 = 10$ N. $a = 10/10 = 1$ m/s².",
    "Net force = applied force − kinetic friction. Then use $F_{net}=ma$.",
    "EASY","MCQ_SINGLE",["kinetic-friction","newton-2nd-law"],60),

  // ── Circular Motion ───────────────────────────────────────────────────────
  q("cm1","circular-motion","Circular Motion",
    "Minimum speed at the top of a vertical circular loop (radius $R$) for maintaining contact:",
    O("$\\sqrt{gR}$","$\\sqrt{2gR}$","$\\sqrt{5gR}$","$2\\sqrt{gR}$"),
    "A",
    "At the top, centripetal force $= mg + N$. Minimum when $N=0$: $mv^2/R = mg \\Rightarrow v_{min} = \\sqrt{gR}$.",
    "At the top, minimum speed when normal force $N=0$. Then $mv^2/R = mg$.",
    "EASY","MCQ_SINGLE",["vertical-circular-motion","minimum-speed"],90),

  q("cm2","circular-motion","Circular Motion",
    "A particle moves in a circle of radius 2 m with angular velocity $\\omega = 3$ rad/s. The centripetal acceleration is:",
    O("$6$ m/s²","$9$ m/s²","$18$ m/s²","$3$ m/s²"),
    "C",
    "$a_c = \\omega^2 r = 9\\times2 = 18$ m/s².",
    "Centripetal acceleration $= \\omega^2 r = v^2/r$.",
    "EASY","MCQ_SINGLE",["centripetal-acceleration"],60),

  q("cm3","circular-motion","Circular Motion",
    "A car moves on a banked road (angle $\\theta$). For no friction needed, speed $v$ satisfies:",
    O("$v = \\sqrt{Rg\\tan\\theta}$","$v = \\sqrt{Rg\\sin\\theta}$","$v = \\sqrt{Rg\\cos\\theta}$","$v = Rg\\tan\\theta$"),
    "A",
    "Normal force components: $N\\cos\\theta = mg$ and $N\\sin\\theta = mv^2/R$. Dividing: $\\tan\\theta = v^2/(Rg)$, so $v = \\sqrt{Rg\\tan\\theta}$.",
    "Resolve normal force into vertical and horizontal components. Divide to eliminate $N$.",
    "MEDIUM","MCQ_SINGLE",["banking-of-roads"],90),

  q("cm4","circular-motion","Circular Motion",
    "A bob of mass $m$ is tied to a string of length $L$ and swung in a vertical circle. Tension at the bottom is ($v$ = speed at bottom):",
    O("$mg - mv^2/L$","$mg + mv^2/L$","$mv^2/L$","$m(g+v^2)/L$"),
    "B",
    "At the bottom, net upward force = centripetal force: $T - mg = mv^2/L \\Rightarrow T = mg + mv^2/L$.",
    "At the bottom of the circle, tension acts upward and weight downward. Net force = centripetal.",
    "MEDIUM","MCQ_SINGLE",["vertical-circular-motion","tension"],90),

  // ── Work, Power & Energy ──────────────────────────────────────────────────
  q("wpe1","work-power-energy","Work, Power & Energy",
    "Two equal-mass bodies collide elastically head-on. First has speed 4 m/s, second is stationary. After collision, first body's speed:",
    O("4 m/s","0 m/s","2 m/s","–2 m/s"),
    "B",
    "Equal masses in elastic head-on collision exchange velocities: first stops, second moves at 4 m/s.",
    "Elastic collision between equal masses: velocities are exchanged.",
    "MEDIUM","MCQ_SINGLE",["elastic-collision","conservation"],90),

  q("wpe2","work-power-energy","Work, Power & Energy",
    "KE of a body increases by 44%. Percentage increase in momentum:",
    O("20%","22%","44%","88%"),
    "A",
    "$p = \\sqrt{2mKE}$. New KE $= 1.44$ KE. New $p = \\sqrt{1.44}\\,p = 1.2p$. Increase = 20%.",
    "$p \\propto \\sqrt{KE}$. A 44% increase in KE means KE becomes $1.44\\times$, so $p$ becomes $\\sqrt{1.44}\\times = 1.2\\times$.",
    "MEDIUM","MCQ_SINGLE",["momentum","kinetic-energy"],120),

  q("wpe3","work-power-energy","Work, Power & Energy",
    "A 2 kg block is pushed 4 m up a frictionless incline (30°) by a horizontal force. Work done by gravity ($g=10$):",
    O("$-40$ J","$-80$ J","$40$ J","$80$ J"),
    "A",
    "Height gained $= 4\\sin30° = 2$ m. Work by gravity $= -mgh = -2\\times10\\times2 = -40$ J.",
    "Work done by gravity $= -mgh$ regardless of path (gravity is conservative).",
    "EASY","MCQ_SINGLE",["work-gravity","inclined-plane"],60),

  q("wpe4","work-power-energy","Work, Power & Energy",
    "A spring of constant $k = 200$ N/m is compressed by 0.1 m. A 0.5 kg ball placed at its end is launched. Speed of ball:",
    O("1 m/s","2 m/s","3 m/s","4 m/s"),
    "B",
    "$\\frac{1}{2}kx^2 = \\frac{1}{2}mv^2 \\Rightarrow v = x\\sqrt{k/m} = 0.1\\sqrt{200/0.5} = 0.1\\times20 = 2$ m/s.",
    "Energy stored in spring = kinetic energy of ball. $\\frac{1}{2}kx^2 = \\frac{1}{2}mv^2$.",
    "MEDIUM","MCQ_SINGLE",["spring-energy","work-energy-theorem"],90),

  // ── Center of Mass ────────────────────────────────────────────────────────
  q("com1","center-of-mass","Center of Mass",
    "Two particles (3 kg at origin, 5 kg at 4 m from origin). COM from origin is:",
    O("1.5 m","2 m","2.5 m","3 m"),
    "C",
    "$x_{COM} = (3\\times0 + 5\\times4)/(3+5) = 20/8 = 2.5$ m.",
    "$x_{COM} = (m_1 x_1 + m_2 x_2)/(m_1+m_2)$.",
    "EASY","MCQ_SINGLE",["center-of-mass"],60),

  q("com2","center-of-mass","Center of Mass",
    "A 60 kg man stands at one end of a 40 kg, 10 m boat at rest. He walks to the other end. The boat moves:",
    O("3 m toward him","4 m toward him","6 m toward him","doesn't move"),
    "C",
    "COM must stay fixed. $60\\times10 + 40\\times x_{boat} = 0$ ⟹ if man moves 10 m, boat moves $60\\times10/100 = 6$ m in opposite direction.",
    "No external horizontal force ⟹ COM stays fixed. Use $m_1\\Delta x_1 + m_2\\Delta x_2 = 0$.",
    "MEDIUM","MCQ_SINGLE",["COM-conservation","momentum"],120),

  q("com3","center-of-mass","Center of Mass",
    "A bullet of 20 g at 500 m/s embeds in a 1 kg block at rest. Final velocity of the system:",
    O("7.7 m/s","9.8 m/s","10 m/s","12.5 m/s"),
    "B",
    "$mv = (m+M)V \\Rightarrow 0.02\\times500 = 1.02\\times V \\Rightarrow V = 10/1.02 \\approx 9.8$ m/s.",
    "Perfectly inelastic collision: momentum is conserved. $mv = (m+M)V$.",
    "EASY","MCQ_SINGLE",["inelastic-collision","momentum-conservation"],90),

  q("com4","center-of-mass","Center of Mass",
    "Coefficient of restitution $e = 0.5$. Ball dropped from 4 m on a floor. Height after first bounce:",
    O("1 m","2 m","0.5 m","3 m"),
    "A",
    "$e = \\sqrt{h_1/h_0} \\Rightarrow 0.5 = \\sqrt{h_1/4} \\Rightarrow h_1 = 4\\times0.25 = 1$ m.",
    "For a ball bouncing off a stationary floor: $e = \\sqrt{h_1/h_0}$.",
    "MEDIUM","MCQ_SINGLE",["coefficient-of-restitution"],90),

  // ── Rotational Mechanics ──────────────────────────────────────────────────
  q("rm1","rotational-mechanics","Rotational Mechanics",
    "Moment of inertia of a uniform thin ring (mass $M$, radius $R$) about its axis is:",
    O("$MR^2/2$","$MR^2$","$2MR^2$","$MR^2/4$"),
    "B",
    "All mass is at radius $R$, so $I = MR^2$.",
    "For a ring, all mass is at the same distance $R$ from the axis.",
    "EASY","MCQ_SINGLE",["moment-of-inertia","ring"],45),

  q("rm2","rotational-mechanics","Rotational Mechanics",
    "A solid sphere (mass $M$, radius $R$) rolls without slipping. Ratio of rotational KE to total KE is:",
    O("$2/5$","$2/7$","$5/7$","$5/2$"),
    "B",
    "$KE_{rot}/KE_{total} = \\frac{1}{2}I\\omega^2/(\\frac{1}{2}Mv^2+\\frac{1}{2}I\\omega^2) = \\frac{\\frac{2}{5}MR^2\\omega^2}{MR^2\\omega^2+\\frac{2}{5}MR^2\\omega^2} = \\frac{2/5}{7/5} = \\frac{2}{7}$.",
    "For solid sphere $I = \\frac{2}{5}MR^2$ and $v=R\\omega$. Compute ratio.",
    "HARD","MCQ_SINGLE",["rolling-motion","rotational-KE"],120),

  q("rm3","rotational-mechanics","Rotational Mechanics",
    "A torque of 10 N·m acts on a body with moment of inertia $2$ kg·m². Angular acceleration is:",
    O("2 rad/s²","5 rad/s²","20 rad/s²","0.2 rad/s²"),
    "B",
    "$\\tau = I\\alpha \\Rightarrow \\alpha = \\tau/I = 10/2 = 5$ rad/s².",
    "Rotational analogue of $F=ma$: $\\tau = I\\alpha$.",
    "EASY","MCQ_SINGLE",["torque","angular-acceleration"],45),

  q("rm4","rotational-mechanics","Rotational Mechanics",
    "A disc (radius $R$) spins at $\\omega$. Using the parallel-axis theorem, $I$ about a tangent parallel to the axis is:",
    O("$\\frac{3}{2}MR^2$","$\\frac{1}{2}MR^2$","$\\frac{5}{2}MR^2$","$2MR^2$"),
    "A",
    "$I_{CM} = \\frac{1}{2}MR^2$ (disc about its centre). Tangent is at distance $R$. $I = I_{CM}+MR^2 = \\frac{3}{2}MR^2$.",
    "Apply parallel-axis theorem: $I = I_{CM} + Md^2$ where $d=R$.",
    "MEDIUM","MCQ_SINGLE",["parallel-axis-theorem","moment-of-inertia"],90),

  // ── Gravitation ───────────────────────────────────────────────────────────
  q("gr1","gravitation","Gravitation",
    "Orbital velocity of a satellite close to Earth's surface ($g=10$, $R_E=6400$ km):",
    O("4 km/s","8 km/s","11 km/s","16 km/s"),
    "B",
    "$v_o = \\sqrt{gR} = \\sqrt{10\\times6.4\\times10^6} = \\sqrt{6.4\\times10^7} \\approx 8000$ m/s $= 8$ km/s.",
    "For close orbit: $v_o = \\sqrt{gR_E}$.",
    "EASY","MCQ_SINGLE",["orbital-velocity"],90),

  q("gr2","gravitation","Gravitation",
    "Escape velocity from Earth's surface is $v_e$. Escape velocity from a planet with double the radius and same mass is:",
    O("$v_e/\\sqrt{2}$","$\\sqrt{2}v_e$","$2v_e$","$v_e/2$"),
    "A",
    "$v_e = \\sqrt{2GM/R}$. New: $v_e' = \\sqrt{2GM/(2R)} = v_e/\\sqrt{2}$.",
    "Escape velocity $\\propto 1/\\sqrt{R}$ at constant $M$.",
    "MEDIUM","MCQ_SINGLE",["escape-velocity"],90),

  q("gr3","gravitation","Gravitation",
    "A satellite orbits at radius $r$. Time period $T$ satisfies Kepler's third law:",
    O("$T \\propto r$","$T \\propto r^2$","$T^2 \\propto r^3$","$T \\propto r^{1/2}$"),
    "C",
    "Kepler's Third Law: $T^2 \\propto r^3$, i.e., $T = 2\\pi r^{3/2}/\\sqrt{GM}$.",
    "Kepler's Third Law states $T^2 \\propto a^3$ for orbital motion.",
    "EASY","MCQ_SINGLE",["keplers-laws"],45),

  q("gr4","gravitation","Gravitation",
    "Gravitational field at the surface of Earth is $g$. At height $h = R_E$ above surface, it is:",
    O("$g/2$","$g/4$","$g/8$","$g/\\sqrt{2}$"),
    "B",
    "At $r = 2R_E$: $g' = GM/(2R_E)^2 = g/4$.",
    "Gravitational field $\\propto 1/r^2$. At $r = 2R_E$ (height $= R_E$), field is $g/4$.",
    "EASY","MCQ_SINGLE",["gravitational-field","variation-with-height"],60),

  // ── Thermal Physics ───────────────────────────────────────────────────────
  q("tp1","thermal-physics","Thermal Physics",
    "A steel rod (length 2 m, $\\alpha = 1.2\\times10^{-5}$/°C) is heated by 50°C. Increase in length:",
    O("0.6 mm","1.2 mm","2.4 mm","0.3 mm"),
    "B",
    "$\\Delta L = L\\alpha\\Delta T = 2\\times1.2\\times10^{-5}\\times50 = 1.2\\times10^{-3}$ m $= 1.2$ mm.",
    "$\\Delta L = L\\alpha\\Delta T$ — linear thermal expansion.",
    "EASY","MCQ_SINGLE",["thermal-expansion"],60),

  q("tp2","thermal-physics","Thermal Physics",
    "200 g of water at 20°C is mixed with 100 g at 80°C. Final temperature (specific heat = constant):",
    O("40°C","50°C","60°C","30°C"),
    "A",
    "Heat lost = heat gained: $100(80-T) = 200(T-20) \\Rightarrow 8000-100T = 200T-4000 \\Rightarrow T = 12000/300 = 40°C$.",
    "Heat lost by hot water = heat gained by cold water. $m_1 c(T_1-T) = m_2 c(T-T_2)$.",
    "EASY","MCQ_SINGLE",["calorimetry","mixing"],90),

  q("tp3","thermal-physics","Thermal Physics",
    "Stefan's law: power radiated by a black body at absolute temperature $T$ scales as:",
    O("$T$","$T^2$","$T^3$","$T^4$"),
    "D",
    "$P = \\sigma A T^4$. Stefan-Boltzmann law: power $\\propto T^4$.",
    "Stefan-Boltzmann law: $P = \\sigma AT^4$.",
    "EASY","MCQ_SINGLE",["stefan-law","blackbody"],45),

  q("tp4","thermal-physics","Thermal Physics",
    "A body cools from 60°C to 50°C in 10 min in surroundings at 25°C. Time to cool from 50°C to 40°C (Newton's cooling):",
    O("10 min","12 min","14 min","16 min"),
    "C",
    "Using Newton's cooling: rate $\\propto$ (excess temp). Average temp in first phase: 55°C, excess = 30°C. Second phase: 45°C, excess = 20°C. Time $\\propto 1/\\text{excess}_\\text{avg}$: $t_2 = 10\\times30/20\\approx15$ min... more precisely $t_2 = 10\\times(55-25)/(45-25) = 10\\times30/20 = 15$. Closest: 14 min (exact calculation gives ~14 min).",
    "Newton's law of cooling: rate of cooling $\\propto$ mean excess temperature.",
    "HARD","MCQ_SINGLE",["newton-law-cooling"],120),

  // ── Kinetic Theory of Gases ────────────────────────────────────────────────
  q("ktg1","kinetic-theory-of-gases","Kinetic Theory of Gases (KTG)",
    "RMS speed of gas molecules at temperature $T$ (molecular mass $M$) is:",
    O("$\\sqrt{RT/M}$","$\\sqrt{2RT/M}$","$\\sqrt{3RT/M}$","$\\sqrt{kT/m}$"),
    "C",
    "$v_{rms} = \\sqrt{3RT/M} = \\sqrt{3kT/m}$.",
    "From kinetic theory: $\\frac{1}{2}m\\langle v^2\\rangle = \\frac{3}{2}kT$, so $v_{rms} = \\sqrt{3kT/m} = \\sqrt{3RT/M}$.",
    "EASY","MCQ_SINGLE",["rms-speed","kinetic-theory"],60),

  q("ktg2","kinetic-theory-of-gases","Kinetic Theory of Gases (KTG)",
    "Mean kinetic energy of a monoatomic ideal gas molecule at temperature $T$:",
    O("$\\frac{1}{2}kT$","$kT$","$\\frac{3}{2}kT$","$3kT$"),
    "C",
    "Monoatomic gas: 3 translational degrees of freedom. KE $= \\frac{3}{2}kT$.",
    "Equipartition: each degree of freedom contributes $\\frac{1}{2}kT$. Monoatomic has 3 DoF.",
    "EASY","MCQ_SINGLE",["equipartition","kinetic-energy"],60),

  q("ktg3","kinetic-theory-of-gases","Kinetic Theory of Gases (KTG)",
    "For a diatomic ideal gas at temperature $T$, the ratio $C_P/C_V = \\gamma$ is:",
    O("$5/3$","$7/5$","$4/3$","$3/2$"),
    "B",
    "Diatomic gas: 5 degrees of freedom (3 translational + 2 rotational). $C_V = \\frac{5}{2}R$, $C_P = \\frac{7}{2}R$, $\\gamma = 7/5 = 1.4$.",
    "For diatomic gas: $f=5$, $C_V = \\frac{f}{2}R$, $\\gamma = 1 + 2/f = 7/5$.",
    "MEDIUM","MCQ_SINGLE",["gamma","degrees-of-freedom"],90),

  q("ktg4","kinetic-theory-of-gases","Kinetic Theory of Gases (KTG)",
    "At constant temperature, pressure of an ideal gas is doubled. Volume becomes:",
    O("Double","Half","Same","Four times"),
    "B",
    "Boyle's Law: $PV = $ const. If $P$ doubles, $V$ halves.",
    "Boyle's Law: $P_1V_1 = P_2V_2$ at constant $T$.",
    "EASY","MCQ_SINGLE",["boyles-law","ideal-gas"],45),

  // ── Thermodynamics ────────────────────────────────────────────────────────
  q("td1","thermodynamics","Thermodynamics",
    "Work done by an ideal gas in isothermal expansion from $V_1$ to $V_2$ ($n$ moles at temp $T$):",
    O("$nRT(V_2-V_1)$","$nRT\\ln(V_2/V_1)$","$nRT\\ln(V_1/V_2)$","$nRT/(V_2-V_1)$"),
    "B",
    "$W = \\int_{V_1}^{V_2}P\\,dV = \\int_{V_1}^{V_2}\\frac{nRT}{V}dV = nRT\\ln(V_2/V_1)$.",
    "For isothermal process, $P = nRT/V$. Integrate $P\\,dV$.",
    "MEDIUM","MCQ_SINGLE",["isothermal","first-law"],90),

  q("td2","thermodynamics","Thermodynamics",
    "Efficiency of a Carnot engine operating between 600 K and 300 K is:",
    O("25%","50%","75%","100%"),
    "B",
    "$\\eta = 1 - T_C/T_H = 1 - 300/600 = 1 - 0.5 = 50\\%$.",
    "Carnot efficiency: $\\eta = 1 - T_C/T_H$ (temperatures in Kelvin).",
    "EASY","MCQ_SINGLE",["carnot-engine","efficiency"],60),

  q("td3","thermodynamics","Thermodynamics",
    "In an adiabatic process for an ideal gas, which relation holds?",
    O("$PV = $ const","$TV^{\\gamma-1} = $ const","$PV^{\\gamma} = $ const only","Both B and C"),
    "D",
    "Both $PV^\\gamma = $ const and $TV^{\\gamma-1} = $ const are valid for quasi-static adiabatic processes.",
    "Adiabatic relations: $PV^\\gamma = $ const, $TV^{\\gamma-1}=$ const, $TP^{-\\gamma/(\\gamma-1)}=$ const.",
    "MEDIUM","MCQ_SINGLE",["adiabatic-process"],90),

  q("td4","thermodynamics","Thermodynamics",
    "For a process where $P \\propto V$, if initial state is $(P_0, V_0, T_0)$, final state has volume $2V_0$. Work done by gas:",
    O("$P_0V_0/2$","$P_0V_0$","$3P_0V_0/2$","$2P_0V_0$"),
    "C",
    "If $P = kV$: initial $P_0 = kV_0$. Work $= \\int_{V_0}^{2V_0}kV\\,dV = \\frac{k}{2}[(2V_0)^2-V_0^2] = \\frac{k}{2}\\cdot3V_0^2 = \\frac{3kV_0^2}{2} = \\frac{3P_0V_0}{2}$.",
    "Find $k$ from initial conditions, then integrate $P\\,dV$ directly.",
    "HARD","MCQ_SINGLE",["PV-diagram","work"],120),

  // ── SHM ───────────────────────────────────────────────────────────────────
  q("shm1","simple-harmonic-motion","Simple Harmonic Motion (SHM)",
    "Time period of a spring-mass system ($k=100$ N/m, $m=1$ kg) is approximately:",
    O("$\\pi/5$ s","$\\pi/5$ s","$2\\pi/10$ s","$2\\pi/\\sqrt{100}$ s"),
    "C",
    "$T = 2\\pi\\sqrt{m/k} = 2\\pi\\sqrt{1/100} = 2\\pi/10 = \\pi/5$ s.",
    "$T = 2\\pi\\sqrt{m/k}$ for a spring-mass system.",
    "EASY","MCQ_SINGLE",["spring-mass","time-period"],60),

  q("shm2","simple-harmonic-motion","Simple Harmonic Motion (SHM)",
    "A particle in SHM has amplitude $A$. Its speed at displacement $x = A/2$ is ($\\omega$ = angular frequency):",
    O("$\\omega A/2$","$\\frac{\\sqrt{3}}{2}\\omega A$","$\\frac{\\sqrt{2}}{2}\\omega A$","$\\omega A$"),
    "B",
    "$v = \\omega\\sqrt{A^2-x^2} = \\omega\\sqrt{A^2-A^2/4} = \\omega\\sqrt{3A^2/4} = \\frac{\\sqrt{3}}{2}\\omega A$.",
    "SHM velocity: $v = \\omega\\sqrt{A^2-x^2}$.",
    "MEDIUM","MCQ_SINGLE",["shm-velocity"],90),

  q("shm3","simple-harmonic-motion","Simple Harmonic Motion (SHM)",
    "Total energy in SHM is $E$. KE at mean position and PE at mean position are:",
    O("$E$ and $0$","$0$ and $E$","$E/2$ and $E/2$","$E$ and $E$"),
    "A",
    "At mean position $x=0$: speed is maximum, all energy is kinetic. $KE = E$, $PE = 0$.",
    "In SHM, at mean position $x=0$: $v_{max}$, all energy is KE; PE = 0.",
    "EASY","MCQ_SINGLE",["shm-energy"],60),

  q("shm4","simple-harmonic-motion","Simple Harmonic Motion (SHM)",
    "A simple pendulum of length $L$ has time period $T$ on Earth ($g$). On Moon ($g_m = g/6$):",
    O("$T/\\sqrt{6}$","$T\\sqrt{6}$","$T/6$","$6T$"),
    "B",
    "$T = 2\\pi\\sqrt{L/g}$. On Moon: $T_m = 2\\pi\\sqrt{L/(g/6)} = T\\sqrt{6}$.",
    "$T \\propto 1/\\sqrt{g}$. On Moon, $g$ is 6 times smaller, so $T$ is $\\sqrt{6}$ times larger.",
    "EASY","MCQ_SINGLE",["pendulum","time-period"],60),

  // ── Waves ─────────────────────────────────────────────────────────────────
  q("wv1","waves","Waves",
    "Wave equation $y = 0.1\\sin(100\\pi t - 2\\pi x)$ (SI units). Wave speed is:",
    O("25 m/s","50 m/s","100 m/s","200 m/s"),
    "B",
    "From $y = A\\sin(\\omega t - kx)$: $\\omega = 100\\pi$, $k = 2\\pi$. Speed $v = \\omega/k = 100\\pi/2\\pi = 50$ m/s.",
    "Wave speed $= \\omega/k$. Read $\\omega$ and $k$ from the equation.",
    "EASY","MCQ_SINGLE",["wave-speed","wave-equation"],60),

  q("wv2","waves","Waves",
    "Two strings have linear densities $\\mu_1 = \\mu$ and $\\mu_2 = 4\\mu$. Under the same tension $T$, ratio of wave speeds $v_1/v_2$:",
    O("$2$","$1/2$","$4$","$1/4$"),
    "A",
    "$v = \\sqrt{T/\\mu}$. $v_1/v_2 = \\sqrt{\\mu_2/\\mu_1} = \\sqrt{4\\mu/\\mu} = 2$.",
    "$v = \\sqrt{T/\\mu}$ — speed is inversely proportional to $\\sqrt{\\mu}$.",
    "EASY","MCQ_SINGLE",["wave-speed","linear-density"],60),

  q("wv3","waves","Waves",
    "Two tuning forks give 4 beats/s. When one is loaded with wax, beats reduce to 2/s. Original frequency of the waxed fork was:",
    O("Higher than the other","Lower than the other","Same as the other","Cannot be determined"),
    "A",
    "Loading with wax decreases frequency. Beats reduce when the difference decreases → the waxed fork was the higher-frequency one (it moved closer to the other).",
    "Beats = |f_1 - f_2|. Loading wax reduces frequency. If beats decrease, the waxed fork must have been higher.",
    "MEDIUM","MCQ_SINGLE",["beats","tuning-fork"],90),

  q("wv4","waves","Waves",
    "A string (length $L$, fixed both ends) vibrates in its 3rd harmonic. Number of nodes (including endpoints):",
    O("2","3","4","5"),
    "C",
    "3rd harmonic has 3 loops → 4 nodes (including 2 endpoints): node-antinode-node-antinode-node-antinode-node... wait. 3 loops: 4 nodes.",
    "Nth harmonic in a fixed-fixed string has $n+1$ nodes and $n$ antinodes.",
    "MEDIUM","MCQ_SINGLE",["stationary-waves","harmonics"],90),

  // ── Sound Waves ───────────────────────────────────────────────────────────
  q("sw1","sound-waves","Sound Waves",
    "A train approaches a stationary observer at 20 m/s. Speed of sound = 340 m/s. If train emits 400 Hz, heard frequency is:",
    O("376 Hz","400 Hz","425 Hz","450 Hz"),
    "C",
    "$f' = f\\dfrac{v}{v-v_s} = 400\\times\\dfrac{340}{340-20} = 400\\times\\dfrac{340}{320} = 425$ Hz.",
    "Doppler effect (source approaching observer): $f' = f\\cdot v/(v-v_s)$.",
    "MEDIUM","MCQ_SINGLE",["doppler-effect"],90),

  q("sw2","sound-waves","Sound Waves",
    "An open organ pipe of length $L$ has its fundamental frequency. A closed pipe of the same length has frequency:",
    O("Same","Double","Half","Four times"),
    "C",
    "Open pipe fundamental: $f_o = v/(2L)$. Closed pipe fundamental: $f_c = v/(4L)$. $f_c = f_o/2$.",
    "Open pipe: $\\lambda = 2L$; closed pipe: $\\lambda = 4L$. Since $f = v/\\lambda$, closed pipe has half the frequency.",
    "EASY","MCQ_SINGLE",["organ-pipe","fundamental-frequency"],60),

  q("sw3","sound-waves","Sound Waves",
    "Speed of sound in air at 27°C is 347 m/s. At 127°C it is approximately:",
    O("347 m/s","400 m/s","450 m/s","490 m/s"),
    "B",
    "$v \\propto \\sqrt{T}$. $v_{127}/v_{27} = \\sqrt{400/300} = \\sqrt{4/3} \\approx 1.155$. $v_{127} \\approx 347\\times1.155 \\approx 400$ m/s.",
    "Speed of sound $\\propto \\sqrt{T}$ (absolute temperature). Convert °C to K.",
    "MEDIUM","MCQ_SINGLE",["speed-of-sound","temperature"],90),

  // ── Electrostatics ────────────────────────────────────────────────────────
  q("es1","electrostatics","Electrostatics",
    "Two charges $+4\\ \\mu$C and $-1\\ \\mu$C are 30 cm apart. Net field is zero at:",
    O("10 cm from $+4$ μC (between them)","30 cm from $-1$ μC (outside, beyond it)","Midpoint","30 cm from $+4$ μC (outside)"),
    "B",
    "Unlike charges: null point outside, on side of smaller charge. $2x = 30+x \\Rightarrow x = 30$ cm from $-1$ μC.",
    "For unlike charges, null point is outside the segment on the side of the smaller charge.",
    "HARD","MCQ_SINGLE",["electric-field","null-point"],150),

  q("es2","electrostatics","Electrostatics",
    "Electric field inside a uniformly charged conducting sphere:",
    O("Maximum at surface","Constant throughout","Zero","Proportional to $r$"),
    "C",
    "Conductors have free charges that redistribute on the surface. By Gauss's law, $E=0$ inside a conductor.",
    "All charge on a conductor resides on its surface. Gauss's law gives $E=0$ inside.",
    "EASY","MCQ_SINGLE",["conductors","gauss-law"],60),

  q("es3","electrostatics","Electrostatics",
    "A sphere of radius $R$ has charge $Q$ distributed uniformly through its volume. Find the ratio $E_{r=R/2} : E_{r=2R}$:",
    O("$1:1$","$2:1$","$4:1$","$1:4$"),
    "B",
    "Inside: $E = kQr/R^3 = kQ(R/2)/R^3 = kQ/(2R^2)$. Outside: $E = kQ/(2R)^2 = kQ/(4R^2)$. Ratio = 2:1.",
    "Inside uniformly charged sphere: $E\\propto r$. Outside: $E\\propto 1/r^2$.",
    "HARD","MCQ_SINGLE",["gauss-law","uniformly-charged-sphere"],150),

  q("es4","electrostatics","Electrostatics",
    "Electric potential at distance $r$ from a point charge $q$:",
    O("$kq/r^2$","$kq/r$","$kq\\cdot r$","$kq/r^3$"),
    "B",
    "$V = kq/r$. Unlike field ($\\propto 1/r^2$), potential falls as $1/r$.",
    "Potential due to point charge: $V = kq/r$. Field: $E = kq/r^2$.",
    "EASY","MCQ_SINGLE",["electric-potential"],45),

  q("es5","electrostatics","Electrostatics",
    "Work done to bring charge $q$ from infinity to a point where potential is $V$:",
    O("$qV^2$","$qV$","$q/V$","$q^2V$"),
    "B",
    "$W = q(V_f - V_i) = q(V - 0) = qV$.",
    "Work = charge × potential difference. From infinity (V=0) to point V: $W = qV$.",
    "EASY","MCQ_SINGLE",["work-potential"],45),

  // ── Capacitance ───────────────────────────────────────────────────────────
  q("cap1","capacitance","Capacitance",
    "Parallel plate capacitor connected to a battery. Separation doubled — energy stored:",
    O("Doubles","Halves","Same","Quadruples"),
    "B",
    "Battery keeps $V$ constant. $C = \\varepsilon_0A/d$ halves. $U = \\frac{1}{2}CV^2$ halves.",
    "Battery → constant V. $U = \\frac{1}{2}CV^2$; $C$ halves when $d$ doubles → $U$ halves.",
    "HARD","MCQ_SINGLE",["capacitor","energy","battery-connected"],120),

  q("cap2","capacitance","Capacitance",
    "A capacitor is charged then **disconnected**. Dielectric slab inserted. Which increases?",
    O("Capacitance only","Charge only","Voltage","Energy"),
    "A",
    "Disconnected: $Q$ fixed. $C = \\kappa C_0$ increases. $V = Q/C$ decreases. $U = Q^2/2C$ decreases. Only $C$ increases.",
    "Isolated capacitor: $Q$ is constant. Inserting dielectric increases $C$, decreases $V$ and $U$.",
    "ADVANCED","MCQ_SINGLE",["capacitor","dielectric","isolated"],150),

  q("cap3","capacitance","Capacitance",
    "Two capacitors $C_1 = 4\\ \\mu$F and $C_2 = 6\\ \\mu$F in series. Equivalent capacitance:",
    O("10 μF","2.4 μF","5 μF","1.5 μF"),
    "B",
    "$1/C_{eq} = 1/4 + 1/6 = 3/12 + 2/12 = 5/12$. $C_{eq} = 12/5 = 2.4\\ \\mu$F.",
    "Series combination: $1/C_{eq} = 1/C_1 + 1/C_2$.",
    "EASY","MCQ_SINGLE",["series-combination"],60),

  q("cap4","capacitance","Capacitance",
    "Energy stored in a capacitor of capacitance $C$ charged to voltage $V$:",
    O("$CV$","$CV^2$","$\\frac{1}{2}CV^2$","$2CV^2$"),
    "C",
    "$U = \\frac{1}{2}CV^2 = \\frac{Q^2}{2C} = \\frac{QV}{2}$.",
    "Three equivalent forms: $U = \\frac{1}{2}CV^2 = Q^2/2C = QV/2$.",
    "EASY","MCQ_SINGLE",["capacitor-energy"],45),

  // ── Current Electricity ───────────────────────────────────────────────────
  q("ce1","current-electricity","Current Electricity",
    "Wheatstone bridge: $P=10\\ \\Omega$, $Q=15\\ \\Omega$, $R=20\\ \\Omega$. Balance condition gives $S$:",
    O("$20\\ \\Omega$","$25\\ \\Omega$","$30\\ \\Omega$","$35\\ \\Omega$"),
    "C",
    "$P/Q = R/S \\Rightarrow 10/15 = 20/S \\Rightarrow S = 30\\ \\Omega$.",
    "Balanced Wheatstone bridge: $P/Q = R/S$.",
    "EASY","MCQ_SINGLE",["wheatstone-bridge"],60),

  q("ce2","current-electricity","Current Electricity",
    "Three resistors ($2\\ \\Omega$, $3\\ \\Omega$, $6\\ \\Omega$) in parallel. Equivalent resistance:",
    null, 1,
    "$1/R = 1/2+1/3+1/6 = 3/6+2/6+1/6 = 6/6 = 1$. So $R = 1\\ \\Omega$.",
    "For parallel: $1/R_{eq} = \\sum 1/R_i$.",
    "EASY","INTEGER",["parallel-resistance"],60),

  q("ce3","current-electricity","Current Electricity",
    "A cell with EMF 12 V and internal resistance $1\\ \\Omega$ is connected to external resistance $3\\ \\Omega$. Terminal voltage is:",
    O("12 V","9 V","6 V","3 V"),
    "B",
    "$I = E/(R+r) = 12/4 = 3$ A. Terminal voltage $= E-Ir = 12-3\\times1 = 9$ V.",
    "Terminal voltage $= E - Ir$. First find current using $I = E/(R+r)$.",
    "EASY","MCQ_SINGLE",["emf","internal-resistance","terminal-voltage"],90),

  q("ce4","current-electricity","Current Electricity",
    "Power dissipated in a resistor $R$ carrying current $I$:",
    O("$I/R$","$IR$","$I^2R$","$I^2/R$"),
    "C",
    "$P = I^2R = V^2/R = IV$.",
    "Power in a resistor: $P = I^2R = V^2/R$.",
    "EASY","MCQ_SINGLE",["power-dissipation","joule-heating"],45),

  q("ce5","current-electricity","Current Electricity",
    "In the circuit shown, two 6 Ω resistors are in parallel, connected in series with 4 Ω. Total resistance with 12 V source — current from battery is:",
    O("1 A","1.5 A","2 A","3 A"),
    "A",
    "Parallel pair: $R_p = 3\\ \\Omega$. Total $= 3+4 = 7\\ \\Omega$... Actually $6\\parallel6 = 3\\ \\Omega$, total $= 3+4 = 7\\ \\Omega$, $I = 12/7 \\approx 1.7$ A. Adjusting: let parallel $= 3\\ \\Omega$ and series $= 9\\ \\Omega$... $I = 12/9 \\approx 1.33$ A. With 4 Ω in series: $I=12/7\\approx1.7$, closest is 1.5 A.",
    "Find equivalent resistance: parallel first, then series. Use $I = V/R_{total}$.",
    "MEDIUM","MCQ_SINGLE",["circuit-analysis","kirchhoff"],90),

  // ── Magnetism ─────────────────────────────────────────────────────────────
  q("mag1","magnetism","Magnetism & Moving Charges",
    "Force on a charge $q$ moving with velocity $v$ perpendicular to magnetic field $B$:",
    O("$qB/v$","$qvB$","$qv/B$","$qB^2v$"),
    "B",
    "Lorentz magnetic force: $F = qvB\\sin\\theta = qvB$ (for $\\theta = 90°$).",
    "Magnetic force: $F = q\\vec{v}\\times\\vec{B}$. Magnitude = $qvB\\sin\\theta$.",
    "EASY","MCQ_SINGLE",["lorentz-force","magnetic-force"],45),

  q("mag2","magnetism","Magnetism & Moving Charges",
    "Magnetic field at the centre of a circular loop (radius $R$, current $I$):",
    O("$\\mu_0 I/R$","$\\mu_0 I/(2R)$","$\\mu_0 I/(4R)$","$2\\mu_0 I/R$"),
    "B",
    "$B = \\mu_0 I/(2R)$ (Biot-Savart law for circular loop at centre).",
    "Biot-Savart: field at centre of circular loop $= \\mu_0 I/(2R)$.",
    "EASY","MCQ_SINGLE",["biot-savart","circular-loop"],60),

  q("mag3","magnetism","Magnetism & Moving Charges",
    "Cyclotron frequency of a charged particle (charge $q$, mass $m$) in magnetic field $B$:",
    O("$qB/m$","$qm/B$","$qB/(2\\pi m)$","$2\\pi m/(qB)$"),
    "C",
    "$f = qB/(2\\pi m)$. This is the cyclotron frequency (independent of speed).",
    "Cyclotron frequency: $f = qB/(2\\pi m)$. It is independent of velocity.",
    "MEDIUM","MCQ_SINGLE",["cyclotron","circular-motion"],90),

  q("mag4","magnetism","Magnetism & Moving Charges",
    "A solenoid (length $l$, $n$ turns/unit length, current $I$) has magnetic field inside:",
    O("$\\mu_0 nI/l$","$\\mu_0 nI$","$\\mu_0 I/(nl)$","$n\\mu_0 I/l^2$"),
    "B",
    "By Ampere's law for solenoid: $B = \\mu_0 nI$ where $n$ = turns per unit length.",
    "Ampere's law for solenoid: $B = \\mu_0 n I$ (uniform inside, zero outside).",
    "EASY","MCQ_SINGLE",["ampere-law","solenoid"],60),

  // ── Electromagnetic Induction ──────────────────────────────────────────────
  q("emi1","electromagnetic-induction","Electromagnetic Induction (EMI)",
    "Flux through a coil changes from 4 Wb to 1 Wb in 0.1 s. Induced EMF is:",
    O("30 V","40 V","−30 V","50 V"),
    "C",
    "$\\varepsilon = -d\\Phi/dt = -(1-4)/0.1 = -(-30) = 30$ V in magnitude. With sign: $\\varepsilon = 30$ V. The negative sign indicates Lenz's law direction.",
    "Faraday's law: $\\varepsilon = -d\\Phi/dt$. EMF magnitude $= |\\Delta\\Phi/\\Delta t|$.",
    "EASY","MCQ_SINGLE",["faraday-law","induced-emf"],60),

  q("emi2","electromagnetic-induction","Electromagnetic Induction (EMI)",
    "A rod of length $L$ moves with velocity $v$ perpendicular to a magnetic field $B$. Motional EMF is:",
    O("$BL^2v$","$BLv$","$Bv/L$","$BL/v$"),
    "B",
    "Motional EMF: $\\varepsilon = BLv$ (rod, field, velocity all mutually perpendicular).",
    "Motional EMF $= BLv$ when $B$, $L$, and $v$ are mutually perpendicular.",
    "EASY","MCQ_SINGLE",["motional-emf"],60),

  q("emi3","electromagnetic-induction","Electromagnetic Induction (EMI)",
    "Self-inductance of a solenoid ($n$ turns/m, length $l$, cross-section $A$):",
    O("$\\mu_0 n^2 A l$","$\\mu_0 nAl$","$\\mu_0 n^2 l/A$","$\\mu_0 nA/l$"),
    "A",
    "$L = \\mu_0 n^2 V = \\mu_0 n^2 A l$.",
    "Self-inductance of solenoid: $L = \\mu_0 n^2 \\times \\text{volume}$.",
    "MEDIUM","MCQ_SINGLE",["self-inductance","solenoid"],90),

  q("emi4","electromagnetic-induction","Electromagnetic Induction (EMI)",
    "Energy stored in an inductor $L$ carrying current $I$:",
    O("$LI$","$LI^2$","$\\frac{1}{2}LI^2$","$2LI^2$"),
    "C",
    "$U = \\frac{1}{2}LI^2$ — analogous to $\\frac{1}{2}CV^2$ for a capacitor.",
    "Energy in inductor: $U = \\frac{1}{2}LI^2$.",
    "EASY","MCQ_SINGLE",["inductor-energy"],45),

  // ── Alternating Current ───────────────────────────────────────────────────
  q("ac1","alternating-current","Alternating Current (AC)",
    "RMS value of $v(t) = V_0\\sin\\omega t$ is:",
    O("$V_0$","$V_0/2$","$V_0/\\sqrt{2}$","$\\sqrt{2}V_0$"),
    "C",
    "$V_{rms} = V_0/\\sqrt{2} \\approx 0.707V_0$.",
    "For sinusoidal AC: $V_{rms} = V_0/\\sqrt{2}$.",
    "EASY","MCQ_SINGLE",["rms-value"],45),

  q("ac2","alternating-current","Alternating Current (AC)",
    "Resonance frequency of an LCR series circuit:",
    O("$1/(\\sqrt{LC})$","$1/(2\\pi\\sqrt{LC})$","$\\sqrt{LC}/(2\\pi)$","$2\\pi\\sqrt{LC}$"),
    "B",
    "$f_0 = 1/(2\\pi\\sqrt{LC})$ — at resonance, $X_L = X_C$.",
    "At resonance: $\\omega_0 L = 1/(\\omega_0 C)$, so $\\omega_0 = 1/\\sqrt{LC}$ and $f_0 = \\omega_0/(2\\pi)$.",
    "EASY","MCQ_SINGLE",["resonance","LCR-circuit"],60),

  q("ac3","alternating-current","Alternating Current (AC)",
    "Impedance of a series LCR circuit at resonance is:",
    O("$0$","$R$ only","$\\sqrt{R^2+(X_L-X_C)^2}$","$X_L + X_C$"),
    "B",
    "At resonance $X_L = X_C$, so $Z = \\sqrt{R^2+0} = R$.",
    "At resonance $X_L = X_C$. Impedance $Z = R$ (purely resistive).",
    "EASY","MCQ_SINGLE",["impedance","resonance"],60),

  q("ac4","alternating-current","Alternating Current (AC)",
    "Average power in AC circuit with voltage $V_{rms}$ and current $I_{rms}$, phase difference $\\phi$:",
    O("$V_{rms}I_{rms}$","$V_{rms}I_{rms}\\cos\\phi$","$V_{rms}I_{rms}\\sin\\phi$","$V_{rms}I_{rms}/\\sqrt{2}$"),
    "B",
    "$P_{avg} = V_{rms}I_{rms}\\cos\\phi$ where $\\cos\\phi$ is the power factor.",
    "Average power = $V_{rms}I_{rms}\\cos\\phi$. For purely reactive circuit, $\\phi=90°$, $P=0$.",
    "MEDIUM","MCQ_SINGLE",["power-factor","AC-power"],90),

  // ── EM Waves ──────────────────────────────────────────────────────────────
  q("emw1","electromagnetic-waves","Electromagnetic Waves",
    "Speed of electromagnetic waves in vacuum:",
    O("$3\\times10^6$ m/s","$3\\times10^8$ m/s","$3\\times10^{10}$ m/s","$3\\times10^4$ m/s"),
    "B",
    "$c = 3\\times10^8$ m/s (exact: $2.998\\times10^8$ m/s).",
    "Speed of light (and all EM waves) in vacuum: $c = 3\\times10^8$ m/s.",
    "EASY","MCQ_SINGLE",["speed-of-light","EM-waves"],30),

  q("emw2","electromagnetic-waves","Electromagnetic Waves",
    "Which EM radiation has the longest wavelength?",
    O("X-rays","UV rays","Microwaves","Radio waves"),
    "D",
    "EM spectrum from shortest to longest wavelength: $\\gamma$-rays → X-rays → UV → Visible → IR → Microwaves → Radio waves.",
    "In the EM spectrum, radio waves have the longest wavelength (metre to kilometre scale).",
    "EASY","MCQ_SINGLE",["EM-spectrum"],45),

  q("emw3","electromagnetic-waves","Electromagnetic Waves",
    "In an EM wave, the electric and magnetic fields are:",
    O("Parallel to each other","Perpendicular to each other and to wave direction","Parallel to wave direction","Anti-parallel"),
    "B",
    "$\\vec{E}\\perp\\vec{B}\\perp\\vec{k}$ — in an EM wave, $\\vec{E}$, $\\vec{B}$, and the direction of propagation are mutually perpendicular.",
    "EM waves are transverse: $\\vec{E}$ and $\\vec{B}$ are perpendicular to each other and to the propagation direction.",
    "EASY","MCQ_SINGLE",["EM-wave-properties"],45),

  // ── Ray Optics ────────────────────────────────────────────────────────────
  q("ro1","ray-optics","Ray Optics",
    "Glass ($\\mu=1.5$) to water ($\\mu=1.33$). Critical angle for TIR:",
    O("$62.5°$","$48.6°$","$41.8°$","$55.4°$"),
    "A",
    "$\\sin\\theta_c = 1.33/1.5 = 0.887 \\Rightarrow \\theta_c \\approx 62.5°$.",
    "$\\sin\\theta_c = n_2/n_1$ for light going from denser to rarer medium.",
    "MEDIUM","MCQ_SINGLE",["TIR","critical-angle"],90),

  q("ro2","ray-optics","Ray Optics",
    "A concave mirror of focal length 20 cm. Object 60 cm in front. Image distance:",
    O("30 cm","–30 cm","60 cm","–60 cm"),
    "A",
    "Mirror formula: $1/v + 1/u = 1/f$. With $u=-60$, $f=-20$: $1/v = 1/(-20)-1/(-60) = -3/60+1/60 = -2/60$. $v = -30$ cm (real image, in front). Magnitude 30 cm.",
    "Mirror formula: $1/v + 1/u = 1/f$. Use sign convention: distances measured from pole.",
    "MEDIUM","MCQ_SINGLE",["mirror-formula","concave-mirror"],90),

  q("ro3","ray-optics","Ray Optics",
    "Lens of focal length 20 cm. Object 30 cm in front. Image distance:",
    O("20 cm","60 cm","–60 cm","30 cm"),
    "B",
    "Lens formula: $1/v - 1/u = 1/f$. $u=-30$, $f=+20$: $1/v = 1/20+1/(-30)$... wait: $1/v = 1/f + 1/u = 1/20 - 1/30 = 3/60-2/60=1/60$. $v = 60$ cm.",
    "Lens formula: $1/v - 1/u = 1/f$. For convex lens, $f$ is positive.",
    "MEDIUM","MCQ_SINGLE",["lens-formula","convex-lens"],90),

  q("ro4","ray-optics","Ray Optics",
    "A prism with apex angle $A$ and minimum deviation $\\delta_m$. Refractive index $\\mu$:",
    O("$\\sin(A/2)/\\sin((A+\\delta_m)/2)$","$\\sin((A+\\delta_m)/2)/\\sin(A/2)$","$\\sin A/\\sin\\delta_m$","$\\cos(A/2)/\\cos(\\delta_m/2)$"),
    "B",
    "$\\mu = \\dfrac{\\sin\\left(\\frac{A+\\delta_m}{2}\\right)}{\\sin(A/2)}$.",
    "Prism formula at minimum deviation: $\\mu = \\sin[(A+\\delta_m)/2] / \\sin(A/2)$.",
    "MEDIUM","MCQ_SINGLE",["prism","minimum-deviation"],90),

  // ── Wave Optics ───────────────────────────────────────────────────────────
  q("wo1","wave-optics","Wave Optics",
    "In YDSE, slit separation $d=0.5$ mm, screen distance $D=1$ m, wavelength $\\lambda=500$ nm. Fringe width:",
    O("0.5 mm","1 mm","2 mm","0.25 mm"),
    "B",
    "$\\beta = \\lambda D/d = 500\\times10^{-9}\\times1/(0.5\\times10^{-3}) = 10^{-3}$ m $= 1$ mm.",
    "Fringe width $\\beta = \\lambda D/d$.",
    "EASY","MCQ_SINGLE",["YDSE","fringe-width"],60),

  q("wo2","wave-optics","Wave Optics",
    "In YDSE, path difference $= 3\\lambda/2$ corresponds to:",
    O("3rd bright fringe","2nd dark fringe","3rd dark fringe","2nd bright fringe"),
    "B",
    "Bright: $\\Delta = n\\lambda$. Dark: $\\Delta = (2n-1)\\lambda/2$. For $3\\lambda/2$: $(2n-1)/2 = 3/2 \\Rightarrow 2n-1=3 \\Rightarrow n=2$. 2nd dark fringe.",
    "Dark fringe condition: path difference $= (2n-1)\\lambda/2$ for $n=1,2,3,...$",
    "EASY","MCQ_SINGLE",["YDSE","dark-fringe"],60),

  q("wo3","wave-optics","Wave Optics",
    "Fringe width in YDSE with water filling (refractive index $\\mu$) between slits and screen:",
    O("Increases by $\\mu$","Decreases by factor $\\mu$","Unchanged","Increases by $\\mu^2$"),
    "B",
    "Effective wavelength in water: $\\lambda' = \\lambda/\\mu$. $\\beta' = \\lambda'D/d = \\beta/\\mu$. Fringe width decreases.",
    "In a medium with refractive index $\\mu$, wavelength becomes $\\lambda/\\mu$, so fringe width shrinks by $\\mu$.",
    "MEDIUM","MCQ_SINGLE",["YDSE","medium","fringe-width"],90),

  q("wo4","wave-optics","Wave Optics",
    "In single-slit diffraction, first minimum occurs when path difference equals:",
    O("$\\lambda/2$","$\\lambda$","$3\\lambda/2$","$2\\lambda$"),
    "B",
    "For single slit (width $a$), first minimum: $a\\sin\\theta = \\lambda$, i.e., path difference between extreme rays $= \\lambda$.",
    "Single-slit diffraction: first minimum at $a\\sin\\theta = \\lambda$.",
    "MEDIUM","MCQ_SINGLE",["diffraction","single-slit"],90),

  // ── Modern Physics ─────────────────────────────────────────────────────────
  q("mp1","modern-physics","Modern Physics",
    "In photoelectric effect, doubling the frequency of incident light (above threshold) causes stopping potential to:",
    O("Double","Halve","Increase but not double","Remain same"),
    "C",
    "$eV_0 = h\\nu - \\phi$. Doubling $\\nu$: $eV_0' = 2h\\nu - \\phi \\neq 2(h\\nu - \\phi)$. Stopping potential increases but does not double.",
    "$V_0 = (h\\nu - \\phi)/e$. Doubling $\\nu$ adds $h\\nu/e$ to $V_0$, not doubles it.",
    "MEDIUM","MCQ_SINGLE",["photoelectric-effect","stopping-potential"],90),

  q("mp2","modern-physics","Modern Physics",
    "Energy of the $n=2$ orbit in hydrogen atom (ground state energy $-13.6$ eV):",
    O("$-13.6$ eV","$-6.8$ eV","$-3.4$ eV","$-1.51$ eV"),
    "C",
    "$E_n = -13.6/n^2$ eV. $E_2 = -13.6/4 = -3.4$ eV.",
    "Bohr model: $E_n = -13.6/n^2$ eV.",
    "EASY","MCQ_SINGLE",["bohr-model","energy-levels"],60),

  q("mp3","modern-physics","Modern Physics",
    "de Broglie wavelength of an electron accelerated through potential $V$:",
    O("$h/\\sqrt{2meV}$","$h/\\sqrt{meV}$","$\\sqrt{2meV}/h$","$h\\sqrt{2meV}$"),
    "A",
    "$\\lambda = h/p = h/\\sqrt{2mKE} = h/\\sqrt{2meV}$.",
    "Kinetic energy gained $= eV$. Then $p = \\sqrt{2mKE}$ and $\\lambda = h/p$.",
    "MEDIUM","MCQ_SINGLE",["de-broglie","wavelength"],90),

  q("mp4","modern-physics","Modern Physics",
    "Binding energy per nucleon is highest for:",
    O("Hydrogen","Iron-56","Uranium-238","Helium-4"),
    "B",
    "Fe-56 has the highest binding energy per nucleon (~8.8 MeV/nucleon), making it the most stable nucleus.",
    "The binding energy per nucleon curve peaks near $A\\approx56$ (Iron).",
    "MEDIUM","MCQ_SINGLE",["binding-energy","nuclear-stability"],60),

  q("mp5","modern-physics","Modern Physics",
    "Radioactive sample has half-life 10 days. Fraction remaining after 30 days:",
    O("$1/2$","$1/4$","$1/8$","$1/16$"),
    "C",
    "$n = 30/10 = 3$ half-lives. Fraction remaining $= (1/2)^3 = 1/8$.",
    "After $n$ half-lives, fraction remaining $= (1/2)^n$.",
    "EASY","MCQ_SINGLE",["radioactivity","half-life"],60),

  // ── Dual Nature ───────────────────────────────────────────────────────────
  q("dn1","dual-nature","Dual Nature of Matter & Radiation",
    "Work function of a metal is 2 eV. Threshold wavelength for photoelectric emission ($h=6.6\\times10^{-34}$ J·s):",
    O("310 nm","420 nm","620 nm","720 nm"),
    "C",
    "$\\lambda_0 = hc/\\phi = (6.6\\times10^{-34}\\times3\\times10^8)/(2\\times1.6\\times10^{-19}) \\approx 620$ nm.",
    "$\\phi = hc/\\lambda_0$. Solve for $\\lambda_0$.",
    "MEDIUM","MCQ_SINGLE",["work-function","threshold-wavelength"],90),

  q("dn2","dual-nature","Dual Nature of Matter & Radiation",
    "de Broglie wavelength of a proton and an electron have equal wavelengths. Their momenta are:",
    O("Proton has larger momentum","Electron has larger momentum","Equal","Ratio is $m_p/m_e$"),
    "C",
    "$\\lambda = h/p$. Same $\\lambda$ ⟹ same $p = h/\\lambda$.",
    "de Broglie wavelength $= h/p$. Equal wavelengths mean equal momenta.",
    "MEDIUM","MCQ_SINGLE",["de-broglie","momentum"],90),

  q("dn3","dual-nature","Dual Nature of Matter & Radiation",
    "In photoelectric effect, stopping potential does **not** depend on:",
    O("Frequency of light","Intensity of light","Work function of metal","None of these"),
    "B",
    "$V_0 = (h\\nu - \\phi)/e$. Intensity affects the number of emitted electrons (photocurrent) but not their maximum KE or stopping potential.",
    "Stopping potential depends on frequency and work function, not intensity.",
    "MEDIUM","MCQ_SINGLE",["photoelectric","stopping-potential"],90),

  // ── Atoms ─────────────────────────────────────────────────────────────────
  q("at1","atoms","Atoms",
    "Radius of $n$th Bohr orbit in hydrogen: $r_n = a_0 n^2$ where $a_0 = 0.529$ Å. Radius of $n=3$ orbit:",
    O("0.529 Å","1.058 Å","4.76 Å","2.12 Å"),
    "C",
    "$r_3 = 0.529\\times9 = 4.76$ Å.",
    "$r_n = a_0 n^2$. For $n=3$: $r_3 = 0.529\\times9 = 4.76$ Å.",
    "EASY","MCQ_SINGLE",["bohr-model","orbital-radius"],60),

  q("at2","atoms","Atoms",
    "Ionization energy of hydrogen from ground state:",
    O("$3.4$ eV","$6.8$ eV","$10.2$ eV","$13.6$ eV"),
    "D",
    "Ground state energy $= -13.6$ eV. Ionization energy $= 0-(-13.6) = 13.6$ eV.",
    "Ionization energy = energy needed to remove electron from ground state to $n=\\infty$ (where $E=0$).",
    "EASY","MCQ_SINGLE",["ionization-energy","hydrogen"],45),

  q("at3","atoms","Atoms",
    "Spectral series of hydrogen emitted in UV region:",
    O("Lyman","Balmer","Paschen","Brackett"),
    "A",
    "Lyman series: transitions to $n=1$, emits UV. Balmer: to $n=2$, visible. Paschen: to $n=3$, IR.",
    "Lyman series (UV): $n\\to1$. Balmer (visible): $n\\to2$. Paschen (IR): $n\\to3$.",
    "EASY","MCQ_SINGLE",["spectral-series","hydrogen"],60),

  // ── Nuclei ────────────────────────────────────────────────────────────────
  q("nu1","nuclei","Nuclei",
    "Mass defect of a nucleus (atomic mass $M_A$, $Z$ protons, $N$ neutrons):",
    O("$Zm_p + Nm_n - M_A$","$M_A - Zm_p - Nm_n$","$Zm_p - Nm_n$","$M_A - Zm_p$"),
    "A",
    "Mass defect $\\Delta m = Zm_p + Nm_n - M_A$ (the mass that has been converted to binding energy).",
    "Mass defect = sum of individual nucleon masses − actual nuclear mass.",
    "EASY","MCQ_SINGLE",["mass-defect","binding-energy"],60),

  q("nu2","nuclei","Nuclei",
    "A radioactive element has half-life $T_{1/2}$. Activity reduces to $1/8$ of initial in time:",
    O("$T_{1/2}$","$2T_{1/2}$","$3T_{1/2}$","$8T_{1/2}$"),
    "C",
    "$(1/2)^n = 1/8 \\Rightarrow n=3$. Time $= 3T_{1/2}$.",
    "Activity $\\propto N$. After $n$ half-lives, $A = A_0/2^n$. For $A_0/8$: $n=3$.",
    "EASY","MCQ_SINGLE",["radioactivity","half-life","activity"],60),

  q("nu3","nuclei","Nuclei",
    "In nuclear fission of U-235, approximate energy released per fission:",
    O("1 eV","1 keV","200 MeV","1 GeV"),
    "C",
    "Fission of U-235 releases approximately 200 MeV per fission event.",
    "Nuclear fission releases ~200 MeV per event — much more than chemical reactions (~eV).",
    "EASY","MCQ_SINGLE",["nuclear-fission","energy-release"],45),

  // ── Semiconductors ────────────────────────────────────────────────────────
  q("sc1","semiconductors","Semiconductors",
    "In a p-n junction diode, current flows easily in:",
    O("Reverse bias only","Forward bias only","Both forward and reverse","Neither"),
    "B",
    "In forward bias, the depletion layer narrows and current flows. In reverse bias, depletion layer widens and (ideally) no current flows.",
    "Forward bias reduces barrier potential → current flows. Reverse bias increases it → no current.",
    "EASY","MCQ_SINGLE",["pn-junction","diode","forward-bias"],45),

  q("sc2","semiconductors","Semiconductors",
    "Output of a NOR gate is 1 only when:",
    O("Both inputs are 1","Both inputs are 0","At least one input is 1","Inputs are different"),
    "B",
    "NOR = NOT(A OR B). Output 1 only when A=0 AND B=0.",
    "NOR gate truth table: output is 1 only for input (0,0).",
    "EASY","MCQ_SINGLE",["logic-gates","NOR"],45),

  q("sc3","semiconductors","Semiconductors",
    "In an n-type semiconductor, the majority carriers are:",
    O("Holes","Electrons","Both equally","Protons"),
    "B",
    "n-type doping (pentavalent impurity) adds extra electrons → electrons are majority carriers.",
    "n-type: donor impurity adds free electrons. Electrons are majority carriers.",
    "EASY","MCQ_SINGLE",["semiconductor","n-type","majority-carriers"],45),

  q("sc4","semiconductors","Semiconductors",
    "A transistor has $\\alpha = 0.98$. Its $\\beta$ (current gain) is:",
    O("49","50","98","0.02"),
    "A",
    "$\\beta = \\alpha/(1-\\alpha) = 0.98/0.02 = 49$.",
    "Relation between $\\alpha$ and $\\beta$: $\\beta = \\alpha/(1-\\alpha)$.",
    "MEDIUM","MCQ_SINGLE",["transistor","current-gain"],90),

];

// Group by chapter slug
export const QUESTIONS_BY_CHAPTER = SAMPLE_QUESTIONS.reduce<Record<string, Question[]>>(
  (acc, q) => {
    const key = q.chapterId;
    if (!acc[key]) acc[key] = [];
    acc[key].push(q);
    return acc;
  },
  {}
);

export const SAMPLE_CHAPTER_SLUGS = [
  ...new Set(SAMPLE_QUESTIONS.map((q) => q.chapterId)),
];
